version: "3"

services: 
    web:
        build: 
            context: .
            dockerfile: prod.dockerfile
        ports: 
            - "5000:80"
        networks: 
            - aspdotnetcore-network
    postgres:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: user
        networks: 
            - aspdotnetcore-network  
networks: 
    aspdotnetcore-network:
        driver: bridge
        


